name = "cf-agents-cf4242"
main = "src/index.ts"
compatibility_date = "2025-09-23"
account_id = "c2e2d197f9b85f61e1981fec59d4eda0"
workers_dev = true

[assets]
directory = "public"

[ai]
binding = "AI"
remote = true

[[durable_objects.bindings]]
name = "MyAgent"
class_name = "MyAgent"

# Migration history must include the first time you created the DO:
[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyAgent"]

# (optional future tag; leave empty)
[[migrations]]
tag = "v2"

# Vectorize
[[vectorize]]
binding    = "MEM_INDEX"
index_name = "mem-index"
